gethostbyname:gethostbyname.c gethostbyaddr
	gcc -g -Wall gethostbyname.c -o gethostbyname
gethostbyaddr:gethostbyaddr.c
	gcc -g -Wall gethostbyaddr.c -o gethostbyaddr
clean:
	rm -f gethostbyname gethostbyaddr
