tcp_unblock_server:tcp_unblock_server.c tcp_unblock_client
	gcc -g -Wall -o tcp_unblock_server tcp_unblock_server.c

tcp_unblock_client:tcp_unblock_client.c
	gcc -g -Wall -o tcp_unblock_client tcp_unblock_client.c

clean:
	rm -f tcp_unblock_server
	rm -f tcp_unblock_client
